---

# SAVVY/2024-11-21: Kubernetes has added beta support for swap:
#   https://kubernetes.io/blog/2023/08/24/swap-linux-beta/
# CALSO:
#   https://github.com/ehashman/k-enhancements/blob/kep-2400/keps/sig-node/2400-node-swap/README.md#summary
#   https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2400-node-swap
#   https://github.com/kubernetes/kubernetes/issues/53533
#   https://github.com/kubernetes/kubernetes/issues/7294
#   https://discuss.kubernetes.io/t/swap-off-why-is-it-necessary/6879

- name: Disable swap for current session
  command: swapoff -a
  become: true

# THANX: Author was gonna use 'lineinfile' but found a useful 'replace' example:
#   https://www.reddit.com/r/linuxadmin/comments/flzx5r/comment/fl1uaoz/
# REFER/2024-11-21: Author's swapfile mount on LM 21.3:
#   /swapfile                                 none            swap    sw              0       0
# - ALTLY: We could use 'ansible.posix.mount' to remove the relevant swapfile
#   mount, but author would rather keep it, commented, for remindability.
# - ALTLY: Something simple like this command would also work:
#     sed -i /etc/fstab -e '/\bswap\b/ s/^\(.*\)/#\1/'
- name: Disable swap permanently in /etc/fstab (persists reboots)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: true
  become: true
  notify: daemon-reload

# DUNNO: Some Kubernetes discussions suggest also *masking* the service
# so it cannot be started.
# - I'm unsure this is absolutely necessary, and didn't test before
#   having done it. But can't hurt, either.
# E.g.:
#   $ sudo systemctl mask swapfile.swap
#   $ ls -la /etc/systemd/system/swapfile.swap
#   /etc/systemd/system/swapfile.swap -> /dev/null
# - WRKLG/2024-11-21: Author's LM 21.3 / Before removing from /etc/fstab
#   (though after `sudo swapoff -a`):
#     $ systemctl --type swap
#       UNIT LOAD ACTIVE SUB DESCRIPTION
#     0 loaded units listed. Pass --all to see loaded but inactive units, too.
#
#     $ systemctl --type swap --all
#       UNIT          LOAD   ACTIVE   SUB  DESCRIPTION
#       swapfile.swap loaded inactive dead /swapfile
#
#     $ sudo systemctl show swapfile.swap
#     ...
#     LoadState=loaded
#     SourcePath=/etc/fstab
#
#     $ sudo systemctl status swapfile.swap
#          Loaded: loaded (/etc/fstab; generated)
#          Active: inactive (dead) since Tue 2024-10-29 19:56:58 CDT; 3 weeks 1 day ago
#            What: /swapfile
#     ...
#
#     $ sudo systemctl cat swapfile.swap
#     # Automatically generated by systemd-fstab-generator
#     ...
# - Author's LM 21.3 / After removing from /etc/fstab and masking:
#     $ systemctl --type swap --all
#       UNIT LOAD ACTIVE SUB DESCRIPTION
#     0 loaded units listed.
#
#     $ sudo systemctl show swapfile.swap
#     ...
#     LoadState=masked
#
#     $ sudo systemctl status swapfile.swap
#     Unit swapfile.swap could not be found.
#
#     $ sudo systemctl cat swapfile.swap
#     # Unit swapfile.swap is masked.
# - DUNNO: The following Ansible module does not work as I thought it might:
#     fatal: [localhost]: FAILED! => {"changed": false, "msg":
#       "Could not find the requested service swapfile.swap: host"}
#   - Same if I try "name: swapfile" or "name: swap" instead.
#
#     - name: Mask swap service so it cannot be started
#       ansible.builtin.systemd_service:
#         name: swapfile.swap
#         enabled: false
#         masked: true
#       become: true
#
# So we'll just be blunt.
- name: Mask swap service so it cannot be started
  ansible.builtin.command: systemctl mask swapfile.swap
  become: true

