---

# PREQU: This task assumes you've previously setup iptables and UFW.
# - It merely adjust the rules for specific Kubernetes ports.
#
# CXREF: See the zoidy_troglodyte role for firewall setup tasks:
#   https://github.com/landonb/zoidy_troglodyte
#   https://github.com/landonb/zoidy_troglodyte/blob/release/tasks/setup-ufw-firewall.yml

# ***

# CXREF: See `man 8 iptables-extensions` for --dport/--destination-port docs.
- name: Add ip6tables rules for user-specified TCP service ports
  ansible.builtin.shell: >
    /sbin/{{ item[0] }} \
      -A INPUT \
      -p tcp \
      --dport {{ item[1] }} \
      -j ACCEPT
  become: yes
  notify: persist iptables
  loop: "{{ ['iptables', 'ip6tables'] | product(extras_firewall_allow_ports_tcp) | list }}"
  when: extras_firewall_allow_ports_tcp | length > 0

# E.g., sudo ufw allow <item>/tcp
# - UTEST: E.g.,
#     [ "$(uname)" = "Linux" ] &&
#       localip="$(ip route get 1 | head -1 | sed 's/ uid .*//' | awk '{ print $NF }')"
#     [ "$(uname)" = "Darwin" ] &&
#       localip="$(ipconfig getifaddr en0)"
#     # From host you're configuring
#     @testhost $ nc -l ${localip} 6443 -v
#     # From another host
#     @otherhost $ nc testhost 6443 -v
- name: "Add ufw rules for user-specified TCP service ports (if you've defined any)"
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  become: yes
  notify: persist iptables
  loop: "{{ extras_firewall_allow_ports_tcp }}"
  when: extras_firewall_allow_ports_tcp | length > 0

