---
# E.g., sudo systemctl restart docker
- name: restart docker
  service:
    name: docker
    state: "{{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: docker_service_manage | bool
  become: true

# E.g., sudo systemctl restart containerd
- name: restart containerd
  ansible.builtin.service:
    name: containerd
    state: "{{ containerd_restart_handler_state }}"
  # Ignore errors in check mode (--check), aka dry run.
  # REFER: https://docs.ansible.com/ansible/2.8/user_guide/playbooks_checkmode.html
  ignore_errors: "{{ ansible_check_mode }}"
  when: containerd_service_manage | bool
  become: true

# E.g., sudo service netfilter-persistent save
- name: persist iptables
  # Note: This creates /etc/iptables/rules.v4|v6
  ansible.builtin.command: service netfilter-persistent save
  become: true

# E.g., sudo systemctl daemon-reload
- name: daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

